# Generated by Django 4.2.4 on 2023-08-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotas_arais', models.FloatField()),
                ('pasodinimo_data', models.DateField()),
                ('sodinimas_is_seklu', models.BooleanField(default=False)),
                ('sodinuku_pikiavimas', models.DateField(blank=True, null=True)),
                ('sodinuku_perkelimas_lysviuose', models.DateTimeField(blank=True, null=True)),
                ('tresimas', models.DateField(blank=True, null=True)),
                ('laistymas', models.DateField(blank=True, null=True)),
                ('purkstymas', models.DateField(blank=True, null=True)),
                ('derliaus_nuemimas', models.DateField(blank=True, null=True)),
                ('pastabos', models.TextField(blank=True, null=True)),
                ('savininkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100)),
                ('aprasymas', models.TextField()),
                ('vieta', models.CharField(max_length=100)),
                ('zeme', models.CharField(max_length=100)),
                ('iranga', models.CharField(max_length=200)),
                ('siltnamis_laukas', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SodoDarbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darbo_data', models.DateField()),
                ('pavadinimas', models.CharField(max_length=100)),
                ('aprasymas', models.TextField()),
                ('darzas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.darzas')),
            ],
        ),
        migrations.AddField(
            model_name='darzas',
            name='veisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.veisle'),
        ),
    ]
